### PR TITLE
djds/dev

### PR DESCRIPTION
**Pull request by djds**
- [style] Update pre-commit hooks
- [style] Remove trailing whitespace, add trailing newline
- [doc] Lint README, CONTRIBUTING
- [ci.github] Lint markdown
- [ci.circleci] Lint YAML
- [ci.drone] Autoformat drone config
- [worker] Consolidate python tools confi into pyproject.toml
- [worker] Use multistage build for container image
- [worker] Add document delimiter to config.yml.sample
- [worker] Lint requirements.txt
- [graphql] Replace path string concatenation with os.path.join
- [graphql] Replace string formatting with f-strings
- [graphql] Replace python calls to exit with sys.exit
- [graphql] Configure flake8 with setup.cfg
- [graphql] Lint check_indicator
- [graphql] Lint local_exporter
- [graphql] Lint local_synchronizer
- [graphql] Lint python lib
- [graphql] Lint lib.dicts
- [graphql] Lint lib.snortparser
- [graphql] Add lib.utils, lib.messages
- [graphql] Remove trailing comma in tsconfig.json
- [graphql] Add pyproject.toml
- test] Remove testLocalImporter var
- [ci.drone] Update nikolaik/python-nodejs:python3.9,}10-nodejs16-alpine

### CODE REVIEW

**Review by SamuelHassine — APPROVED** [review]

**Comment by nor3th** [comment]
Hey @djds 

Could you please pull the current master branch? I am not entirely sure if the failing tests are related to your changes or were already like this before.

Regards

**Comment by djds** [comment]
> Hey @djds
> 
> Could you please pull the current master branch? I am not entirely sure if the failing tests are related to your changes or were already like this before.
> 
> Regards

Rebased off `master` and force-pushed.

**Comment by djds** [comment]
Tests fixed per this tidbit: b4e2ed5bdcf82cb9f9e3263dce0a2f5a8fa7fc3a

**Comment by nor3th** [comment]
I am really sorry for bothering you one last time, but please resolve the open conflicts. Otherwise I can't merge your PR :disappointed:

**Comment by nor3th** [comment]
Thank you very much!!

**Pull request merged**
