### PR TITLE
Be able to select language for Ai text generation (#7299)

### LINKED ISSUE #7299: When using AI, to generate text, be able to select the language and pre-fill with the user profile lang
## Use case

When using AI, to generate text, be able to select the language and pre-fill with the user profile lang

### PR DESCRIPTION
**Pull request by frapuks**
### Proposed changes

* New language field in ask ai form in Report
* Using this language in prompt
* Manage the default value
* Create a dedicated languages list for future implemetation of ai languages
* Add platform_language in RootSettingsFragment
* Manage the forgotten translation in the ask ai form

### Related issues

* close #7299 
* doc : https://github.com/OpenCTI-Platform/docs/pull/208

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Comments

Default value (in order) : user language, platform language, locale language
Locale language is the browser language if it's supported by OpenCTI (1 of 7 supported language), or English.

### CODE REVIEW

**Review by Archidoit — DISMISSED** [review]

**Comment by Archidoit** [comment]
(To be merged in the dev branch)

**Comment by Archidoit** [comment]
In japanese, some words are not translated: 
image

**Comment by Archidoit** [comment]
All the translations appear in the backend log : 
image

**Comment by frapuks** [comment]
Finally, it works better with English name of languages in the prompt : `- The report should be in German language.` in place of `- The report should be in de-de language.`

**Comment by Archidoit** [comment]
@frapuks It's indeed better but still not fully translated : 
image

**Review by Archidoit — APPROVED** [review]

**Pull request merged**
