### PR TITLE
Update overview.md

### PR DESCRIPTION
**Pull request by c-APT-ure**
fixed image paths

relative image paths seem broken in several MD files (images not displaying)

### CODE REVIEW

**Comment by SamuelHassine** [comment]
Hello @c-APT-ure, are you sure? You dont see the image here: https://opencti-platform.github.io/docs/usage/reports-create?

**Comment by c-APT-ure** [comment]
Hi Samuel,

on that url the images display fine, no problem. but here the image src is
absolut and not relative as in the MD files.

the problem is when looking at the MD files on github e.g.

https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-documentation/docs/usage/reports-create.md


Created report

https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-documentation/docs/usage/assets/usage/report_created.png

-> 404

Created report
https://github.com/OpenCTI-Platform/opencti/blob/master/opencti-documentation/docs/assets/usage/report_created.png

-> 200

also see attached screenshots for more details.

hopefully that help making my changes more clear.

but maybe i'll just start looking at the docs from your url instead.

Cheers,
Tom

**Comment by SamuelHassine** [comment]
Yes @c-APT-ure, the documentation is not "viewable" directly on Github, it was developed to be read on the website https://opencti-platform.github.io/docs. Your changes will break this documentation so I cannot approve it. We will try to find a solution to be able to propose both of the approaches.

**Comment by c-APT-ure** [comment]
Sorry, my bad, I can live with that, so forget about my changes.

I didn't know that the docs usually are available like this.

I'm still mostly noob at this Github stuff.

**Comment by SamuelHassine** [comment]
Sorry about that. But still, thanks a lot for your PR and your involvment!

**Pull request closed without merging**
