### PR TITLE
[frontend] add fields that can be made mandatory in Malware Analysis creation form

### LINKED ISSUE #7264: Mandatory fields can block the 'malware analysis' creation
## Description

- For a malware analysis, the update form contains more field than the creation form (i.e. : Configuration Version, Analysis Started)
- In Settings / customization, it's allow to define these fields to 'Mandatory'
- If it's 'Mandatory', you never cann't create a malware analysis because theses fields ane not available in the creation form

## Environment

1. OS (where OpenCTI server runs): Windows 11
2. OpenCTI version: 6.1.8
3. OpenCTI client: frontend 
4. Other environment details: Local & Testing

## Reproducible Steps

1. Go to Settings / Customization / Malware Analysis
2. Update the 'Configuration Version' field
3. Define it 'Mandatory' and save
4. Go to Analyse / Malware Analysis
5. Try to create one
6. Nothing appens

## Expected Output

- To be discussed : May be don't allow to customize these fields (ie : like 'Malware'), or includes these fields in the creation form

## Actual Output

- Nothing appens

## Additional information

- This issue is attached to #6972 

## Screenshots

- Creation form (no 'Configuration Version' field)
image

- Customization
image

### PR DESCRIPTION
**Pull request by Archidoit**
issue: https://github.com/OpenCTI-Platform/opencti/issues/7264

### CODE REVIEW

**Comment by frapuks** [comment]
In the Updating form, we don't have the default value for "Assignee(s)" field.

**Comment by Archidoit** [comment]
@frapuks default values are for creations...

**Review by ValentinBouzinFiligran — APPROVED** [review]

**Comment by ValentinBouzinFiligran** [comment]
Some mandatory fields are in error when changing and others when submitting

**Comment by Archidoit** [comment]
> Some mandatory fields are in error when changing and others when submitting

This behavior is present for other entity types in the platforms. Exemple at an indicator creation with some fields mandatory in customisation : 
image

**Pull request merged**
