### PR TITLE
[Frontend] Implement checkboxes / massive operations in Observations => Infrastructures (#issue/3505)

### PR DESCRIPTION
**Pull request by SarahBocognano**
### Proposed changes

* Implement checkboxes and toolbar for massive operations in Infrastructures
* Refactored the infrastructures files in tsx

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/3505

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by Archidoit** [comment]
Unknown/empty author should be displayed with '-'
image

**Comment by Archidoit** [comment]
Select one infrastructure. Click on 'Enrichement' in the tool bar. Nothing happens.
image

@SarahBocognano Very good point, I notice that this enrichement button doesn't work in several entities with the same error. I'm gonna investigated on that (and maybe open a bug issue or repair it in that pr)

**Comment by Archidoit** [comment]
Select 2 infrastructures. Click on 'Merge' in the toolbar. Missing icons in the opening form:
image

**Comment by marieflorescontact** [comment]
tested locally, it works fine 👌.
- A more general remark about merging: after merging 2 infrastructures (or other entities), we continue to see the 2 merged entities in the list. we have to exit and return to the page or refresh to see only one. 🤔

**Comment by SarahBocognano** [comment]
**Update :** 
Comments fixed and add a fix for other entities in the enrichment button in the toolbar who wasn't working in those entities:
- Malware Analysis
- Incident Responses
- Request for Information
- Request for Takedown
- External Références
- Incident
- Feedback
- Observed Data

**Comment by helene-nguyen** [comment]
Tested locally too, it's working fine :)

And same as @marieflorescontact about update entities with "replace" action type, replace with a new marking (for example) keep the old ones and need to refresh the page to see the correct ones.

@SarahBocognano You are right with @marieflorescontact, unfortunetly that behavior is everywhere on the platform for now. Maybe we can try to find a global solution to repair that @Kedae ?

**Comment by Kedae** [comment]
> Tested locally too, it's working fine :)
> 
> And same as @marieflorescontact about update entities with "replace" action type, replace with a new marking (for example) keep the old ones and need to refresh the page to see the correct ones.
> 
> @SarahBocognano You are right with @marieflorescontact, unfortunetly that behavior is everywhere on the platform for now. Maybe we can try to find a global solution to repair that @Kedae ?

We could try to update the relay store manually, but it's not straight forward. For now we'll just leave it that way

**Comment by SarahBocognano** [comment]
Update: All comments have been responded to. Waiting for another round and/or approuval

**Review by Archidoit — APPROVED** [review]

**Pull request merged**
