### PR TITLE
add Chinese translation in Localization.js

### PR DESCRIPTION
**Pull request by little-roach**
### Proposed changes

* Add Chinese translation in Localization.js 

### Related issues

* If there is any translation to be added or modified in the future, please inform me in time

### Further comments

I have been using OpenCTI for more than 2 year. OpenCTI is a great threat intelligence project. I hope OpenCTI can be better used and promoted in China.

### CODE REVIEW

**Comment by richard-julien** [comment]
This is an amazing job @little-roach! Thanks you!
Could you just fix the linting to have a correct build of your PR?

```
Line 2694:29:  Strings must use singlequote                      quotes
Line 2701:1:   Unexpected tab character                          no-tabs
Line 2701:1:   Expected indentation of 4 spaces but found 1 tab  indent
```

You can check if everything is good using "yarn lint" before pushing the result.
If you have intellij or another code builder you should be able to apply the linting automatically.

Thanks!

**Comment by little-roach** [comment]
Fix incorrect format about cn part in Localization.js

**Comment by little-roach** [comment]
> This is an amazing job @little-roach! Thanks you! Could you just fix the linting to have a correct build of your PR?
> 
> ```
> Line 2694:29:  Strings must use singlequote                      quotes
> Line 2701:1:   Unexpected tab character                          no-tabs
> Line 2701:1:   Expected indentation of 4 spaces but found 1 tab  indent
> ```
> 
> You can check if everything is good using "yarn lint" before pushing the result. If you have intellij or another code builder you should be able to apply the linting automatically.
> 
> Thanks!


@richard-julien 

Format errors about cn part in Localization.js had been fixed, please check it.

**Review by SamuelHassine — APPROVED** [review]

**Comment by SamuelHassine** [comment]
Thanks for this amazing work, we will add the options in the different settings and profile menus.

Great job!

**Pull request merged**
