### PR TITLE
[frontend] fix history filters in activity tab (#6293)

### LINKED ISSUE #6293: In activity tab, the relation history is not working anymore
## Description

Expected:
Left: history of the entity
Right: history of relationships from/to this entity

Actual (same in both):
image

### PR DESCRIPTION
**Pull request by marieflorescontact**
### Proposed changes

* 
*

### Related issues

* [issue/6293](https://github.com/OpenCTI-Platform/opencti/issues/6293)

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by Archidoit** [comment]
context_data.id is also present in StixCoreObjectLatestHistory.ts, StixCoreObjectRelationshipHistory.ts and  StixCoreObjectRelationshipLatestHistory.ts

**Comment by labo-flg** [comment]
Tested OK, but as Cathia said there might be other places to update with the same kind of filter.

**Comment by marieflorescontact** [comment]
> context_data.id is also present in StixCoreObjectLatestHistory.ts, StixCoreObjectRelationshipHistory.ts and StixCoreObjectRelationshipLatestHistory.ts

in these cases I don't think we should filter on `context_data.from_id` and ` context_data.to_id`. it seems to work well as it is now.  @labo-flg @Archidoit

**Comment by labo-flg** [comment]
If these screens refer to the history of the relationship object itself, then context_data.id might be the right filter key, yes.

**Comment by Archidoit** [comment]
@marieflorescontact  what's strange is that I don't see 'id' in the mappings of the 'context_data' attribute (see internalObject-registrationAttributes.ts)

**Comment by labo-flg** [comment]
FYI in elastic, it's present. it's the entity id on which the operation has been logged.

**Review by Archidoit — APPROVED** [review]

**Comment by marieflorescontact** [comment]
I wil add some test before merging

**Comment by marieflorescontact** [comment]
I need more time to implement tests

**Pull request merged**
