### PR TITLE
[backend/frontend] Restore elements from trash + mass operations on the Trash (#1536)

### PR DESCRIPTION
**Pull request by labo-flg**
LOGICAL DELETION CHUNK 2

### Proposed changes
* Add the ability to restore any element from the trash
* add mass operations (toolbar) for confirm / restore elements in the trash

### Related issues

* part of #1536 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by Archidoit** [comment]
Delete a report with status=X.
Delete the X status template.
Restore the report.
The operation of restore is done and the restored report as Status=NEW (NEW beeing the status number 1 of the report workflow status)

**Comment by Archidoit** [comment]
Question : What should happen when we try to restore an entity having a deleted vocabulary as an attribute?

For the moment : the restoration is done without the vocabulary

Exemple:
- Create a report with report_type = 'test_type'
- Delete the 'test_type' vocabulary
- Restore the report
- The report is restored with nothing as report_type

**Comment by Archidoit** [comment]
Bug for an entity with a deleted marking definition

- Delete an entity with marking definition = markingTest
- Delete the marking markingTest
- Go to the Trash page
- An error occurs

image

**Comment by SouadHadjiat** [comment]
PR status :
- All bugs found in bug bash have been resolved, including marking being deleted
- about deleted status, it's a expected behavior : if we try to create a report with a status that doesn't exist, we create it with the first status we find.
- about deleted vocabulary, we didn't change anything in this PR, for now we keep the simple restore.
=> **Waiting for reviews / approval**

**Comment by Archidoit** [comment]
when restoring an entity with lots of relationships, the screen stays frozen on the pop-up for several seconds (we may think it's an error) : 
image

--> maybe add a progression circle

**Review by SouadHadjiat — APPROVED** [review]

**Pull request merged**
