### PR TITLE
Updated Titles to Functional Component Pages Only

### PR DESCRIPTION
**Pull request by dotdev8**
### Proposed changes

* Updated Titles to Functional Component Pages

### Related issues

* Adding Titles to the class component pages causes the page to throw an error.
* On pages where class components were converted to functional components, the title disappears on refresh. Assuming this may have something to do with the saveView() function. 

### Checklist

- [ x] I consider the submitted work as finished
- [ x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments
The pages described in the Related Issues above have not been altered. Only functional component pages where the title persists have been updated. The other pages will be updated in a later PR once the issues have been identified and resolved.

### CODE REVIEW

**Comment by VerboseCat** [comment]
This PR has a known issue. Every time a page renders, both the the custom page title setting function `useConnectedDocumentModifier.setTitle` and the default page title setting function `useDocumentLangModifier` run and set the title. In some instances, the default page title is set after the custom page title is set. This results in the default page title being displayed. I was unable to find a cause or pattern for which components exhibit this bug. 

**The following components from this PR are impacted:**
* Data / Ingestion / OpenCTI Steams (data/Sync.jsx)
* Data / Ingestion / TAXII Feeds (data/IngestionTaxiis.jsx)
* Data / Ingestion / RSS Feeds (data/IngestionRss.jsx)
* Data / Processing / Tasks (data/Tasks.jsx)
* Data / Data sharing / CSV feeds (data/Feed.tsx)
* Data / Data sharing / TAXII collections (data/Taxii.tsx)
* Settings / Parameters (settings/Settings.jsx)
* Settings / Security / Users (settings/Users.jsx)
* Settings / Taxonomies / Vocabularies (settings/Vocabularies.tsx)

**Review by SarahBocognano — APPROVED** [review]

**Comment by SarahBocognano** [comment]
I approved this PR. Just need to resolve the conflit before merging :)

**Comment by VerboseCat** [comment]
@SarahBocognano  Thank you! Could you please change the release branch to release/6.5.0? I do not have the permissions.

**Comment by VerboseCat** [comment]
@Archidoit the merge conflict is resolved and this PR is ready for merge.

**Comment by Archidoit** [comment]
Thanks for your contribution :) The branch has been merged.

**Pull request merged**
