### PR TITLE
'in regards of' filter display in background tasks

### LINKED ISSUE #6416: 'in regards of' filter not correctly displayed in background task
## Description

'in regards of' filter not correctly displayed in background task

## Reproducible Steps
Go to a threat actor group > Knowledge tab.
Select 'Incident' in the right panel.
Select all the entities. Do a background task (exemple: delete button via the toolbar).
The 'in regards of' filter is not correctly displayed : 
image

### PR DESCRIPTION
**Pull request by Archidoit**
issue: https://github.com/OpenCTI-Platform/opencti/issues/6416

### CODE REVIEW

**Review by marieflorescontact — COMMENTED** [review]
`Toolbar` no longer appears if `select all` is checked

image

**Comment by Archidoit** [comment]
> `Toolbar` no longer appears if `select all` is checked
> 
> image

@marieflorescontact This is not related to the original issue. Can you open another issue ?

**Comment by marieflorescontact** [comment]
> > `Toolbar` no longer appears if `select all` is checked
> > image
> 
> @marieflorescontact This is not related to the original issue. Can you open another issue ?

Are you sure? I can't reproduce on testing:
image

**Comment by Archidoit** [comment]
I can't reproduce the bug @marieflorescontact

**Review by marieflorescontact — APPROVED** [review]
tested ok 👌

**Pull request merged**
