### PR TITLE
Filters display in Report Timeline view (#5636)

### LINKED ISSUE #5636: Filters display in Report Timeline view
## Description

In the timeline view of a report, the filters are not correctly displayed (desing).

## Reproducible Steps
Go to a report
Go to the Knowledge tab
Select the 'timeline view'
Add filters via the filters button of the bottom bar
The filters are added next to the button.

Problems:
- the filters are not vertically aligned with the middle of the bottom bar (there are too low)
- if there are too many filters, the end is not displayed (in the capture below, there is a filter after the 'and' and we don't see it) -> either add a tooltip to display the missing filters, either display all the filters (several lines ...)

image

### PR DESCRIPTION
**Pull request by CelineSebe**
### Proposed changes

* I suggest adding the ability to expand the bar when the number of filters becomes significant. This would provide a better user experience.

### Related issues

* #5636

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by marieflorescontact — COMMENTED** [review]
I find it a little odd not to display all the filters if you have enough space to do so.
IMO we should choose between tooltip and the ability to expand the bar.
Capture d'écran 2024-01-26 174946

**Comment by SarahBocognano** [comment]
I agree with @marieflorescontact, also can you maybe just move the 'close' button because I think it's kind of overlap
Capture d'écran 2024-01-29 105217

**Comment by CelineSebe** [comment]
It's a quick fix to display all the filters that were hidden before, only on this screen. The filter team is currently changing the display of each filter.

**Review by marieflorescontact — APPROVED** [review]

**Comment by CelineSebe** [comment]
@marieflorescontact @SarahBocognano I reviewed this issue with JP. This problem exists on all screens where we have filters. However, he thinks that the chevron is not necessary. Thank you for your feedback.

**Comment by CelineSebe** [comment]
@SarahBocognano @marieflorescontact I have implemented some changes, could you please provide a new review for these updates?

**Pull request merged**
