### PR TITLE
FAB replacement for widgets on dashboards

### PR DESCRIPTION
**Pull request by abijahcalderon**
### Proposed changes

* conditionally replaced FAB with split button for create/import widgets on dashboards

### Checklist

- [X] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [X] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by labo-flg** [comment]
We think it will be better to keep on using secondary+primary CTA like you did with the dashboard creation/import FAB, and not a button menu approach.
This requires a bit of redesign as we have a lot of buttons and filters in this view: we can move down the 3 time filte(rs in a new row below the title, it gives more room for the rest.

**Comment by abijahcalderon** [comment]
@labo-flg This PR has been updated and rebased and is ready for re-review!

**Comment by labo-flg** [comment]
Thanks!

**Comment by labo-flg** [comment]
I've reviewed your PR and I think we really need this redesign of the time filters.
We aim for a correct layout under 1400px wide display, and with the 2 buttons it's very crowdy.

I have developped a fix on top of your branch to move the time filters down to a new row in case we're under FAB_REPLACEMENT.
image

I can push that in your branch if you'd like (as well as few styling fixes).

**Review by labo-flg — APPROVED** [review]

**Comment by labo-flg** [comment]
I'm merging this PR and will open another one with my changes.

https://github.com/OpenCTI-Platform/opencti/pull/9464

**Pull request merged**
