### PR TITLE
[frontend] Refactor Filters UI (#3165)

### LINKED ISSUE #3165: Refactor filters display everywhere.
## Use case

Refactor filters display everywhere.

Using a more "shopping website" approach with a left column:

image

### PR DESCRIPTION
**Pull request by jpkha**
### Proposed changes

* Refacto UI Filters with a Notion like approach

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/3165

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by SarahBocognano** [comment]
Missing Trad :
Capture d'écran 2023-11-30 155743
Capture d'écran 2023-11-30 160520


Is it possible to add the possibility to select "aucun label" ?
Capture d'écran 2023-11-30 155929

Isn't it better if we display the "equal" in the right side ? It seems a little busy with the marquage title below 
Capture d'écran 2023-11-30 160317

**Comment by jpkha** [comment]
@SarahBocognano 
Why would you like a "No label" ? You can set label to null. it's the same IMO.

And thank you for your time and the review you did.

**Comment by Archidoit** [comment]
It's possible to have several filters with same key and operator:
- Add the filter 'author' several time from the 'Add a filter' autocomplete field
image

**Comment by Archidoit** [comment]
Big unused space between the list and the 'search' when no filters are selected
image

**Comment by Archidoit** [comment]
strange filters display in Stream lines with the operator between filters of the same key : 
image

**Comment by Archidoit** [comment]
pour l'opérateur par défaut des dates, j'aurai mis 'greater than or equals' plutot que 'greater than'. Tu en penses quoi @Jipegien ? 
image

**Comment by Archidoit** [comment]
Go to a report > Knowledge > add entities.
The spaces between fields are too short above 'search' and too large below
image

**Comment by Archidoit** [comment]
Go to a report > observables Tab
An error occurs
image

**Comment by Jipegien** [comment]
> pour l'opérateur par défaut des dates, j'aurai mis 'greater than or equals' plutot que 'greater than'. Tu en penses quoi @Jipegien ? image

yes

**Comment by Archidoit** [comment]
When there is too many filters in Triggers & Digest : 
image

**Comment by Archidoit** [comment]
In the Stream list, the filters are displayed with a cross (the cross should be present in the stream edition form, not in the streams list) 
same for feed, triggers etc

image

image

**Comment by Archidoit** [comment]
Can't remove a 'deleted' element in a filter
--> I think this bug is not so important but I report it here anyway (maybe resolve after 5.12 or in another issue)

- Go to the reports list
- Do a filtering with 'contains' and select 3 entities
- Delete one of the entities
- Go back to the reports list
- You can't remove the 'deleted' entity from the filter (because it doesn't exist in the list), you should remove the whole filter
image

**Comment by Archidoit** [comment]
Filters keys are not translated in Data > Processing > Tasks
image

**Comment by Archidoit** [comment]
In triggers list, there is no option for the 'trigger type' filter. The options should be: regular digest, live trigger, all
image

same for 'instance trigger' filter
image

**Comment by Archidoit** [comment]
The filtering with 'is empty' / 'is not empty' is not working (no filters sent in the backend query) -> the bug is from the UI
image

**Comment by Archidoit** [comment]
Bad translation of the first column in Events>Sightings
image

The translation should be : 'qualification' (and here it is : filter_x_o...)

**Comment by Archidoit** [comment]
Go to a list of entities. Select all the entities via the checkboxes. An error occurs.
image

**Comment by Archidoit** [comment]
Go to a dashboard. Create a widget of type knowledge. Chose for filter: label=no label
An error occurs.
image

**Comment by Archidoit** [comment]
Go to a dashboard. Create a widget of type knowledge (ex: vertical bar of type knowledge). Select some dynamic source filters. There are not display in orange (but in grey). Same for dynamic target filters.

Bad behavior:
image

Expected behavior: different colors depending of the category of the filters (filters / dynamicFrom / dynamicTo)
image

**Comment by Archidoit** [comment]
Background tasks with empty filters and not working

- Go to global search
- Add a filter on entity type and let the label and ingested filters empty
image

- Do a select all via the checkboxes
- Do a background task
- All the filters are displayed in the background task summary (see screenshort), event the ones that were not filled.
- When we click on 'launch', an error occurs

image

**Comment by Archidoit** [comment]
In the 'Launch a background task' pop-up, the empty label filter is displayed as 'Label: No value', whereas elsewhere in the plateforme it is displayed as 'Label is empty'.
The behavior is working. It's just the display that is not correct.
image

**Comment by jpkha** [comment]
> In the 'Launch a background task' pop-up, the empty label filter is displayed as 'Label: No value', whereas elsewhere in the plateforme it is displayed as 'Label is empty'. The behavior is working. It's just the display that is not correct. image

J'ai corrigé le label et rajouté le not_nil, ça ne géré pas le not_nil car on ne pouvait pas le faire avant.

**Comment by labo-flg** [comment]
If you go to /dashboard/data/entities?sortBy=created_at&orderAsc=false&types=Report

The Report filter is enabled and you will see only reports ; but it's not possible top remove this filtering.

I need to clear my local storage

**Comment by labo-flg** [comment]
Date filtering seems inversed

image

**Comment by Archidoit** [comment]
Filters in trigger lines: too much spaces between the filters and we don't see all the filters if there are too many
image

Same for feeds, taxii, streams etc (same component)

**Comment by Archidoit** [comment]
Go to a 'entity type' filter autocomplete, enter 'CAMP', tap 'ENTER'. Campaign is added
image

When we click elsewhere, Campaign is not added in the values of the entity type filter
image

Comment: if you click on 'Campaign' instead of taping 'ENTER', it's working

**Review by labo-flg — APPROVED** [review]

**Comment by labo-flg** [comment]
We will track all remaining bugs and address them in a dedicated PR.

**Review by Archidoit — APPROVED** [review]

**Pull request merged**
