### PR TITLE
[frontend] Add in bulk entities and some observables in knowledge and containers tabs (#4352)

### PR DESCRIPTION
**Pull request by lndrtrbn**
### Proposed changes

* Can bulk add entities in tab `entities` of a container
* Can bulk add entities in tab `knowledge` of a entity
* Can bulk add observables in tab `observables` of a container
* Can bulk add observables in tab `knowledge` of a entity
* Add some validations on observable creation form

### Related issues

* #4352 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

Chunk 4 of bulk entities + Retrieving work of an other PR for bulk observables

### CODE REVIEW

**Comment by Archidoit** [comment]
In an attack pattern overview, click on 'add' Data components.
image

A panel opens with design problems: 
image

**Comment by Archidoit** [comment]
Can't bulk add directories.

- Go to the Observables tab of a report
- Click on add observables
- Select the directory entity type
- You can't bulk add directories

image

**Comment by Archidoit** [comment]
Working 👍 
Just a remark: when there are duplicates, it is not indicating in bulk creation, but it is in normal creation:

image

**Comment by Archidoit** [comment]
-- An issue example because of the non-detection of duplicates in bulk creation --

In the knowledge tab of a report, create 3 area with the same name.
The duplicates are not detected -> it is indicated that 3 entities will be created.

image

image

image


In the list, 3 entities with the same name appears (whereas if you go to the area lists, you see only 1 logically)

image

If you select one of the 3 'area1', all the others 'area1' automatically get selected

image

**Comment by lndrtrbn** [comment]
@Archidoit 

> Working 👍 Just a remark: when there are duplicates, it is not indicating in bulk creation, but it is in normal creation

Indeed, it has been discussed with product team and the answer was: we do not manage it for now, at least for the detection from duplicates with existing entities in the platform. But I can remove duplicates filled in the textarea you are right, easy to do.

**Review by Archidoit — APPROVED** [review]

**Pull request merged**
