### PR TITLE
[frontend/backend] In malware, make 2 fields "upsertable" (#3117)

### LINKED ISSUE #3117: In malware, make 2 fields "upsertable"
## Use case

In a malware, make "Architecture execution env.” and “Implementation languages" upstartable (update on creation).

### PR DESCRIPTION
**Pull request by Archidoit**
## Notion page
https://www.notion.so/filigran/In-malware-make-2-fields-upsertable-3117-65a3b21dc3a74750a5f52a1ccbd95d4d

## Github issue
https://github.com/OpenCTI-Platform/opencti/issues/3117

### CODE REVIEW

**Comment by RomuDeuxfois** [comment]
Are you sure about adding this fields on creation ?
The issue is about making upsertable, but not existing on UI.

**Comment by Archidoit** [comment]
@RomuDeuxfois yes it was not asked in the issue, but Sam told me to keep these 2 new fields in the creation form.

**Comment by RomuDeuxfois** [comment]
Ok, so it will be good to have it in the edition form too

**Comment by Archidoit** [comment]
@RomuDeuxfois It is already present in the edition form (in the second tab of the form)

**Comment by RomuDeuxfois** [comment]
Oupsi...
Perfect !

**Review by RomuDeuxfois — APPROVED** [review]

**Pull request merged**
