### PR TITLE
[frontend/backend] Dashboard refacto - split view between dashboard and public dashboards

### PR DESCRIPTION
**Pull request by CelineSebe**
### Proposed changes

* left menu: split access view beetween dashboards and public dashboards
* new list with data tables for public dashboards
* rework publicDashboard API to return only the ones I can see
* add actions panel in publi dashboard line (copy link, disabled/enabled, delete (with correct "Can manage" or to be the dashboard creator)
* addition of column shared/not shared in dashboard
* add redirection with "view associated public dashboards", "Go to dashboard" 
* br under feature flag

### Related issues

* #6509 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by Archidoit** [comment]
Differences in navigation headers between custom and public dashboards (no path for Custom dashboards) : 

image


image

**Comment by Archidoit** [comment]
Not enough space between Search and the filters : 
image


By comparison, in Campaigns : 
image

**Comment by Archidoit** [comment]
Write URI in capitals letters in the 'Uri key' filter to be consistant with the column name

image

**Comment by Archidoit** [comment]
The massiv operations proposed are not all available (exemple : 'Add in container' should not be available for a public dashboard) 
image

**Comment by Archidoit** [comment]
Maybe you can make 'Max markings shared' filterable (just enable it in the schema). No reason to make it not filterable

**Comment by Archidoit** [comment]
Why is it not possible to sort public dashboard by URI key ? Is it intentional?

**Comment by Archidoit** [comment]
Export button should not be available for public dashboards : 
image

**Comment by Archidoit** [comment]
In public dashboard, when you click on the top checkbox to select all the dashboards, the action buttons don't appear. You need to check all the dashboards one by one.

**Comment by CelineSebe** [comment]
> Not enough space between Search and the filters : 

It's related to the datatable component; we can't do anything without changing the original component.

The margin in campaigns is the same as the public dashboard on my side.

image

**Comment by CelineSebe** [comment]
> In public dashboard, when you click on the top checkbox to select all the dashboards, the action buttons don't appear. You need to check all the dashboards one by one.

It will be done in the chunk 3

**Review by SarahBocognano — COMMENTED** [review]
image

When I select 'All' the toolbar doesn't display



=> sorry just saw the message above regarding chunk 3 :)

**Comment by SarahBocognano** [comment]
image

Do we want the CTA like "merge", "add to container" & "rules scan" ?

**Comment by CelineSebe** [comment]
> When I select 'All' the toolbar doesn't display

It will be ready for chunk 2

**Comment by CelineSebe** [comment]
> It will be ready for chunk 2

**Comment by SarahBocognano** [comment]
When I try to delete with mass operation an error occurs "The ids are not knowledge". Is this for an another chunk ?

**Comment by CelineSebe** [comment]
> Do we want the CTA like "merge", "add to container" & "rules scan" ?

Same. Resolved in chunk 2.

**Comment by SarahBocognano** [comment]
Ok tested, except the comments who are planned for next chunk it's okay :)

**Review by SarahBocognano — APPROVED** [review]

**Pull request merged**
