### PR TITLE
[frontend] Hide actions in Data tab according to capability (#8243)

### LINKED ISSUE #8243: Hide some actions in "data" tab when user does not have the capability to create/update knowledge
## Description

Hide all action buttons in "Data" tab related to creation or modification of knowledge if the user does not have the capability to create/update knowledge.

Capture d'écran 2024-09-04 095204

## Environment

2. OpenCTI version: 6.2.18

### PR DESCRIPTION
**Pull request by Archidoit**
### Proposed changes
In Data tab of an entity:
- Hide upload button if not the capa 'upload knowledge files'
- Hide the create a workbench button if not the capa 'import knowledge'

In a sighting overview: fix the padding of the external references tab if the user has not the capa to add an external reference

In the content tab of an entity:
hide the upload button if not the capa 'upload knowledge files'

### Related issues
https://github.com/OpenCTI-Platform/opencti/issues/8243

### CODE REVIEW

**Comment by JeremyCloarec** [comment]
Looks good for the changes you made, but is it possible to add a capa check also on the trash button of Uploaded files lines 
image
And on the + button in File on the Content tab:
image

**Comment by Archidoit** [comment]
@JeremyCloarec the '+' button in the Content tab does not require any capability
for the '+' ouf outcome templates, it will be done in our coming chunk

**Comment by JeremyCloarec** [comment]
> @JeremyCloarec the '+' button in the Content tab does not require any capability for the '+' ouf outcome templates, it will be done in our coming chunk

the '+' button does the same `importPush` mutation  as the upload button though, so they should both require the same capability?

**Comment by Archidoit** [comment]
> > @JeremyCloarec the '+' button in the Content tab does not require any capability for the '+' ouf outcome templates, it will be done in our coming chunk
> 
> the '+' button does the same `importPush` mutation as the upload button though, so they should both require the same capability?

it's fixed :)

**Review by JeremyCloarec — APPROVED** [review]

**Pull request merged**
