### PR TITLE
[frontend/backend] Added Customizable Header/Footer banner and Idle Time Screen Masking then Logout

### LINKED ISSUE #3504: Added Customizable Header/Footer banner and Idle Time Screen Masking then Logout
Adds a Customizable Header/Footer text banner with three selectable background colors
Colors are Green, Red, or Yellow
Can be used to denote a message like "Test Data Only in this system", "Highest Level of Data - XYZ", or whatever text you may wish to advertise.
Adds a parameter ("session_idle_timeout": 900000) to config/default.json. This will by default after 15 mins of idle on the application - blank/blur the OpenCTI desktop within the browser and start a countdown timer with the remaining time from the parameter ("session_timeout": 1200000). When the countdown officially ends - you will be logged out.
This is a security related fix in that many organizations have a time limit before a screen must be obscured while idle.
Additionally, on some OpenCTI screens GQL subscriptions reset the session_timeout parameter on idle session - not killing your idle session. This fix - ignores the "automatic GQL subscription queries" - and will correctly terminate an idle session after the official (session_timeout)

### PR DESCRIPTION
**Pull request by ParamConstructor**
### Proposed changes

This change does the following:
* Adds a Customizable Header/Footer text banner with three selectable background colors
   - Colors are Green, Red, or Yellow
   - Can be used to denote a message like "Test Data Only in this system", "Highest Level of Data - XYZ", or whatever text you may wish to advertise.
* Adds a parameter ("session_idle_timeout": 900000) to config/default.json. This will by default after 15 mins of idle on the application - blank/blur the OpenCTI desktop within the browser and start a countdown timer with the remaining time from the parameter ("session_timeout": 1200000). When the countdown officially ends - you will be logged out.
   - This is a security related fix in that many organizations have a time limit before a screen must be obscured while idle.
   - Additionally, on some OpenCTI screens GQL subscriptions reset the session_timeout parameter on idle session - not killing your idle session. This fix - ignores the "automatic GQL subscription queries" - and will correctly terminate an idle session after the official (session_timeout)

### Related issues

None.

### Checklist

- [ X ] I consider the submitted work as finished
- [ X ] I tested the code for its functionality
- [ X ] I wrote test cases for the relevant uses case
    - This was manually tested for this submission. There are Selenuim autotests that are written but not part of the PR to automate the testing.
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ X ] Where necessary I refactored code to improve the overall quality

### Further comments

* There are a large number of GUI files impacted by this change due to the way the OpenCTI page templates are designed and the need to shift/offset components/fields (if enabled) or not shift/offset (if disabled) to prevent possible text overlap of components.

### CODE REVIEW

**Comment by richard-julien** [comment]
Hi @ParamConstructor ,
I tried to check / integrate this feature to integrate it in the upcoming 5.8 but it was not possible due to conflits with the current master branch.

Some operations i htink that needs to be done:
- Rebase from master
- Convert IdleTimeoutLockscreen.js in tsx.
- If IdleTimeout is set to 0 (disable),  IdleTimeoutLockscreen component should not be loaded (+ 0 should be the default static config to need force this behavior for existing platform)

Could be done later
- Add IdleTimeout configuration in the UI instead of static config
- Find a way to disable this timeout in some screens or through a global button for people that display dashboard in fullscreen in command center.

**Comment by ParamConstructor** [comment]
@richard-julien - Rebasing now to catch it up (had been rebasing regularly since submitted - but not in the last 2 weeks)

- Trying to work off today the initial set of must have requests
    - Convert IdleTimeoutLockscreen.js in tsx
    - IdleTimeout is set to 0 (disable), IdleTimeoutLockscreen component should not be loaded
    - Default IdleTimeout to 0 for initial release
- Will attempt today to add the IdleTimeout variable as a configurable GUI option to the newly added Settings-->Security--> Policy page (Page the Consent Messages, Platform Message, and Password Policy config was deployed to recently).

Will table to "future" the - find a way to disable this timeout in some screens or through a global button for people that display dashboard in full screen in command center. Fully understand "why" that might be a request. 

Maybe it would be implemented on the pop-up? After the pop-up displays the first time to warn you that you are on a page that will be logged out in X minutes - you can click "Disable and don't warn on this page again" - and then it just turns the countdown off on the page. That way no "new" button needs to be added to the pages - and it could work on "any page" at that point - just the pop-up has top be displayed 1 time to enact the disable for that page.

Hopefully - if these are in minus that last item - this one can possible make the 5.8 cut or a merge to master early after the official 5.8 release.....

**Comment by ParamConstructor** [comment]
@richard-julien / @Kedae - Updates have been made:
- Rebased to 5.8.2
- Convert IdleTimeoutLockscreen.js to tsx
- IdleTimeout is set to 0 (disable)
    - IdleTimeoutLockscreen components do not load, if disabled
- Default IdleTimeout to 0 for initial release
- A option on the timeout modal has been added of - 'Disable timeout on this page'

Not done:
- The optional request to add the IdleTimeout configuration in the UI instead of static config was not implemented in the PR. This can be handled in a separate PR after a good "location" to add it too is defined.

Bug Fix / Random Fix:
- Padding was added to the bottom of the login widget area after the SSO buttons. If you have the banners turned on, have a consent message that is long, and a platform message that is long - with SSO enabled, those button seem to be too close to the footer banner. So, this was cleaned up.
- The checkbox for consent to monitor didn't "autoscroll" you to the bottom of the page after consent - so that was fixed with a two line code change. Only noticed it if you have a long platform and consent message.

**Comment by richard-julien** [comment]
Thanks @ParamConstructor ! I will take some time to test it again. Looks like there is still a conflict on the PR, can you rebase again? Thanks

**Comment by ParamConstructor** [comment]
@richard-julien - Caught back up to the current git commit of [19ab89c](https://github.com/OpenCTI-Platform/opencti/commit/19ab89ce02d1b2576734fd57da703924b129b23f). This PR is getting tired of running this commit race :-) :turtle: :running_man: :1st_place_medal:

**Comment by ParamConstructor** [comment]
@richard-julien - rebased to [cd9069b](https://github.com/OpenCTI-Platform/opencti/commit/cd9069b91fba5e3c467dc6cfe8420283d729b7b8) - (i.e. 5.8.5 + 1 commit)

**Pull request merged**
