### PR TITLE
Add EQL as an indicator type

### PR DESCRIPTION
**Pull request by dcode**
### Proposed changes

* Adds EQL as an indicator type in the UI
* Adds Python validator using the EQL Python library, implementing the Elasticsearch language variant

### Related issues

* #2094 

### Checklist

- [X] I consider the submitted work as finished
- [ ] I tested the code for its functionality (Not sure how to build and test an environment 😬 )
- [ ] I wrote test cases for the relevant uses case (Didn't see one for the other languages)
- [ ] I added/update the relevant documentation (either on github or on notion) (I'll check this out)
- [X] Where necessary I refactored code to improve the overall quality (Are you opposed to sorting indicator types alphabetically?)

### Further comments

None

### CODE REVIEW

**Review by SamuelHassine — APPROVED** [review]
Thanks a lot for this great PR!

**Review by SamuelHassine — CHANGES_REQUESTED** [review]
The conflict is caused by:
--
183 | parsuricata 0.3.2 depends on lark-parser<0.13.0 and >=0.12.0
184 | eql 0.9.12 depends on lark-parser~=0.11.1

**Comment by dcode** [comment]
I'll work on bumping up the python dependency from the EQL library

**Comment by dcode** [comment]
Related: https://github.com/endgameinc/eql/pull/61

**Comment by dcode** [comment]
This is fixed in the upstream PR, but will probably be early next week before the package is pushed to pypi.

**Comment by SamuelHassine** [comment]
@dcode What do you think about using git+https on the master branch in the requirements.txt to be able to merge?

**Comment by dcode** [comment]
it's been shipped https://github.com/endgameinc/eql/issues/62

https://pypi.org/project/eql/0.9.13/

**Pull request merged**
