### PR TITLE
[Front/Back] Events filters + date filters initial values update (#2881)

### PR DESCRIPTION
**Pull request by Archidoit**
### Proposed changes

Events filters:
- bug fix for invalid date filters: Start date before, start date after, end date before, end date after
- create a filter for Event types
- remove date filters input value if the filter has been removed
- add date filters input values when we come back to a page if filters are selected

### Related issues

https://github.com/OpenCTI-Platform/opencti/issues/2881

### Notion documentation
https://www.notion.so/filigran/Reset-date-filters-initial-values-when-removing-a-filter-via-FilterIconButton-treated-in-2881-70b9a4e4cffa46ff842a4eba24a7330f

### CODE REVIEW

**Comment by RomuDeuxfois** [comment]
Bugs found :
- The events types (label and description) are not translated
image

**Comment by Archidoit** [comment]
@RomuDeuxfois  It seems that it is the case for all types: report_types, incident_type, event_type -->there are not translated since there are vocabularies

**Comment by Kedae** [comment]
image
This is quite unclear :)

**Comment by Kedae** [comment]
image
There is a problem on clearing filters

**Review by Kedae — APPROVED** [review]

**Pull request merged**
