### PR TITLE
[backend] during boot: add try/catch at each step to improve debug (#4090)

### PR DESCRIPTION
**Pull request by shawrupesh**
### Proposed changes

it would be better if there was an error for each thing... like one for cacheManager, one for checkSystemDependencies, one for modules, so we know which part of startup is failing.

### Related issues

*
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by lndrtrbn — CHANGES_REQUESTED** [review]
Thank you for your contribution 😊 Code looks good to me. Just some eslint issues related to spaces around brackets

**Comment by shawrupesh** [comment]
I will fix those space issue

**Comment by shawrupesh** [comment]
Hi @lndrtrbn  Done with the changes, Please review it.
Thank You!

**Review by lndrtrbn — APPROVED** [review]

**Comment by labo-flg** [comment]
@shawrupesh we would be happy to merge your work, but your commits are unsigned. Could you [setup GPG signing on your github account](https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account) please?

Thanks 🙏

**Comment by shawrupesh** [comment]
Hi @labo-flg  Sorry about that, My commits are not virified, I have configured my git, I will raise a new PR with same change with signed commit. I tried to signed my existing commit using rebase but I am getting lots of conflict, So I will go with new PR.

Thanks for the Opportunity!

**Comment by shawrupesh** [comment]
Hi @labo-flg @lndrtrbn @ Please check this PR =https://github.com/OpenCTI-Platform/opencti/pull/6398.

**Pull request closed without merging**
