### PR TITLE
[backend] Migration to remove representative in DB (#7484)

### LINKED ISSUE #7484: In some old instances, we have representative (main / secondary) indexed which leads to issues
## Description

In some old instances, we have representative (main / secondary) indexed which leads to issues.

We need to create a migration to cleanup those attributes:

image

### PR DESCRIPTION
**Pull request by SouadHadjiat**
### Proposed changes

* add migration to remove representative
* remove representative from partialInstanceWithInputs, wasn't used anywhere.

### Related issues

* #7484 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by richard-julien** [comment]
Also need to remove a specific code introduce in #6319

```
export const extractRepresentative = (entityData) => {
  // the representative can already be given (happens when the internals set it to "Restricted")
  if (entityData.representative) {
    return entityData.representative;
  }
```

**Comment by SouadHadjiat** [comment]
> Also need to remove a specific code introduce in #6319
> 
> ```
> export const extractRepresentative = (entityData) => {
>   // the representative can already be given (happens when the internals set it to "Restricted")
>   if (entityData.representative) {
>     return entityData.representative;
>   }
> ```

seems to be linked to this part in middleware (convertAggregateDistributions) : 

```
return {
        ...n,
        entity: {
          id: element.id,
          entity_type: element.entity_type,
          parent_types: element.parent_types,
          representative: { main: 'Restricted', secondary: 'Restricted' }
        }
      };
```

**Comment by richard-julien** [comment]
I missed that :) Thanks for the pointer. 
For this not sure we have an alternative. If you can quickly check with Laurent if he have an idea.
If not we can keep it like this.

**Comment by SouadHadjiat** [comment]
I just saw this method where I wonder why we added a representative (this is what caused updates to index representative)

```
const partialInstanceWithInputs = (instance, inputs) => {
  const inputData = updatedInputsToData(instance, inputs);
  return {
    _index: instance._index,
    internal_id: instance.internal_id,
    entity_type: instance.entity_type,
    representative: extractRepresentative(instance),
    ...inputData,
  };
};
```
Can we remove it here ? @richard-julien

**Review by Kedae — APPROVED** [review]

**Pull request merged**
