### PR TITLE
[frontend] Fix Incorrect redirection in data / relationships for hyper relations (#4774)

### PR DESCRIPTION
**Pull request by marieflorescontact**
### Proposed changes

* Add a check on `node.from` to know if it is a relationship.

### Related issues

* [issue/4774](https://github.com/OpenCTI-Platform/opencti/issues/4774)

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by SamuelHassine** [comment]
Hello,

We need to resolve the correct relationship from / to of the hyper relation and redirect properly.

**Comment by SamuelHassine** [comment]
Ok understood the source code, but the hyper relation can also be on the to.

**Comment by marieflorescontact** [comment]
Is it possible that `from` and `to` are both relationships? @SamuelHassine

**Comment by SamuelHassine** [comment]
It is, but you can ignore this case as it is not used.

**Comment by marieflorescontact** [comment]
@SamuelHassine , 
`const remoteNode = (node.from && !node.from.relationship_type) ? node.from : node.to;`

We either take `to` if `from` is a relationship, or we take `from` if it is not a relationship, which will work if `to` is a relationship, as `from` and `to` cannot, for now, be both relationships.
 Is it correct ? Otherwise what do you suggest?

**Comment by Archidoit** [comment]
When I click on the line of a relationship between a relationship and an entity (an opinion in my case), I'm redirected to this : 
image

**Review by SarahBocognano — COMMENTED** [review]
Tested ✅  The redirect works now. As discussed together, just need to have a information/confirmation about the redirection page

**Pull request merged**
