### PR TITLE
[worker] fix opentelemetry worker dependencies

### PR DESCRIPTION
**Pull request by Archidoit**
fix the running of 'pip install -r requirements.txt' in worker/src
--> update opentelemetry worker dependencies to be consistant with client-python and opencti (version 1.24)

### CODE REVIEW

**Comment by SamuelHassine** [comment]
Sorry Cathia, just pushed the update.

**Comment by Archidoit** [comment]
@SamuelHassine your update doesn't seem to work : 
image

**Comment by helene-nguyen** [comment]
I tried to add this to take into account the both versions

image


But still have a conflict

image


I think this solution can be good, as it takes into account even the 1.22.0 until 1.24.0

```
opentelemetry-api<=1.24.0
opentelemetry-sdk<=1.24.0
```

**Comment by Archidoit** [comment]
I think it's better to use the following code because it's more restrictive : 
image

**Pull request closed without merging**
