### PR TITLE
[frontend] Stix Meta Object details in Investigation graphs (#3986)

### PR DESCRIPTION
**Pull request by Archidoit**
Github issue: https://github.com/OpenCTI-Platform/opencti/issues/3986

To test the issue:
- Go to an investigation graph.
- Click on an entity that has meta relations (labels, markings, kill chain phase or external reference).
- Expand the entity (via a button in the toolbar)
- Click on a meta object. A details panel opens and it has an error.

### CODE REVIEW

**Comment by SamuelHassine** [comment]
@Archidoit I think this is also the case for kill chain phases and external references (all meta objects). Whether we find a way to display them properly or to discard them in a generic approach.

**Comment by Archidoit** [comment]
@SamuelHassine indeed. I'm going to create a detail vue for the meta objects. Maybe I can also create a generic query (and a module) for stixMetaObjects. This will enable to do a single query for all the meta objects, and then display their attribute in the details part.

**Review by SarahBocognano — COMMENTED** [review]
Tested ✅ Works fine

**Comment by Archidoit** [comment]
PR ready for review

**Comment by yassine-ouaamou** [comment]
All good for me 👍

**Review by yassine-ouaamou — APPROVED** [review]

**Pull request merged**
