### PR TITLE
[frontend] Fix Add height / weight do not work (#7118)

### PR DESCRIPTION
**Pull request by SarahBocognano**
### Proposed changes

* Add a validator check to help the user knowing the field is mandatory
* On edit form, when pushes a new height or weight line, put a value instead of null to avoid errors 

### Related issues

* https://github.com/OpenCTI-Platform/opencti/issues/7118

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by Archidoit** [comment]
If we enter something else than a date for the height/weight, the error is not well formatted:
image


You can include this part of code in your dateSeenValidator: 
image

**Comment by Archidoit** [comment]
What is the meaning for the (') unit (simple curiosity)? (I know 'lb' for weight but I don't know (') )

image


@SarahBocognano : this is how we define height in America everytime you'll see a height, I will be like:  5'7" (172cm)

**Comment by Archidoit** [comment]
Usually when a required field is not specified, there is only a red message in the form : 
image


But for height/weight date or measure, a second message appears at the top of the screen "Validation against the schema... " :

image

image

**Comment by CelineSebe** [comment]
When adding a height, after delete the previous date, this date is reinitialized automatically.

@SarahBocognano : Yes I did that on purpose to avoid any error for the user and to show that this field is indeed mandatory and has no sense of use without the date

**Review by lndrtrbn — APPROVED** [review]
I can create TAI with null measure or date for height and weight, I suppose not intended but at least when setting real values it works well

**Pull request merged**
