### PR TITLE
[frontend] open feeds, streams and taxii in new tabs

### PR DESCRIPTION
**Pull request by labo-flg**
### Proposed changes

* opens all feeds, streams and taxii collection windows in new tabs

### Related issues

#4668 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case
- [x] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by labo-flg** [comment]
Still draft, if the issue makes sense I'll open it.

**Comment by richard-julien** [comment]
Not sure about this, its not working by default with crtl+click ?

**Comment by labo-flg** [comment]
Yes it works fine. But I'm getting caught regularly and must reopen the app (which takes some times).

This is just a suggestion, we can discard this PR if you prefer.

**Comment by richard-julien** [comment]
That makes sens i think has the probability you want to open that NOT in a new tab is near 0.
So thats ok for me.

**Comment by labo-flg** [comment]
Ok then let's  review and merge 🚀

**Comment by yassine-ouaamou** [comment]
@labo-flg Can you update the branch with master, please? 

I am getting this error: Your platform data (5.11.8) are too recent to start on version 5.11.4

**Comment by labo-flg** [comment]
> @labo-flg Can you update the branch with master, please?
> 
> I am getting this error: Your platform data (5.11.8) are too recent to start on version 5.11.4

Branch is synced with latest master

**Review by yassine-ouaamou — APPROVED** [review]

**Pull request merged**
