### PR TITLE
[frontend] Base Selenium Auto Test to Login using LocalStrategy then Logout Automatically

### PR DESCRIPTION
**Pull request by ParamConstructor**
This PR adds to the existing base automated test suite for the Frontend project of OpenCTI run using the `yarn test` command line option. This suite adds a Selenium based Chrome driver test that will automatically login and logout of the platform using the base authentication `LocalStrategy`. It updates the Drone PR image for frontend-tests to use Rocky Linux with Chrome browser installed locally to use in the tests via Chrome headless mode.

It additionally adds the frontend running on the opencti-live-start instance of the pipeline. This instance is the instance the chrome browser will connect to for running the frontend GUI tests via the frontend-tests image of the pipeline.

Note: This test suite makes one assumption:
  - It assumes you are developing/running it on a Linux based platform. The `opencti-platform/opencti-front/src/__tests__/selenium/common/file_service.tsx` library doesn't currently account for the OS and the path separator of Windows being '\\' versus '/'. Current OpenCTI development is recommended to be performed on a Linux based platform, the CI/CD pipeline runs, and that is how the Dockerized system is deployed/released.

### Related issues

This test suite disables/excludes the existing `src/__tests__/App.test.tsx` test via the `opencti-platform/opencti-front/vitest.config.ts`. The test is currently used to just verify that the system **_"renders a page"_**. Since the new `auth` test in this PR verifies that this system can be logged in and logged out of - this test is possibly not needed/ duplicative. It has been excluded, but not removed from the source tree in the PR - should it still be required. 

The build does pull down the latest version of Chrome RPM each build - it might be better to stabilize the version of the Chrome RPM pulled down to point to a local Artifactory Repo or even a git repo so you are testing with a known version of Chrome - versus the latest stable - which is updated frequently. However, this currently isn't an issue with the test running.

### Checklist

- [X] I consider the submitted work as finished
- [X] I tested the code for its functionality
- [X] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [X] Where necessary I refactored code to improve the overall quality

### Further comments

There are additional utility libraries provided in this PR off of: `opencti-platform/opencti-front/src/__tests__/selenium/common/*` to assist other developers with future PRs and automated utility activities.

### CODE REVIEW

**Comment by ParamConstructor** [comment]
@richard-julien / @SamuelHassine - Fails the Drone PR run because it doesn't have a `config/development.json` file in the default build. Should I point this to the `config/default.json` by default - or do you have a specific config file that is used by the Drone build?

Sorry - I don't have a mock-up of your Drone PR to test this in - but am realizing that - I suspect the headless tests (i.e. browsing the website without launching a browser to execute the tests) will fail the CI/CD run (would run on your Ubuntu developer desktop - if you have Chrome) - because it will not find Chrome installed by default on the Alpine image (tests use the chrome driver). Alpine has support for "chromium" with `apk add chromium` - check these guys project to have it mimic Chrome (https://github.com/Zenika/alpine-chrome).

**Comment by SamuelHassine** [comment]
Hello @ParamConstructor,

Thanks a lot for this great work. Master branch should be stable for a while. As soon as your PR is rebased, I will take care of it.

Kind regards,
Samuel

**Comment by ParamConstructor** [comment]
@SamuelHassine - I have rebased this PR to 5.9.4 (a3067f0). Thanks.

**Comment by ParamConstructor** [comment]
Relates to base for - https://github.com/OpenCTI-Platform/opencti/issues/1989

**Comment by ParamConstructor** [comment]
@richard-julien / @SamuelHassine - Rebased to 5.10.1 (https://github.com/OpenCTI-Platform/opencti/commit/710c10632d7dd82006e88508fdba1038c994e2c3). Adjudicated pipeline issues - runs Chrome within container (Rocky Linux) and connects to `opencti-live-start` for testing of GUI. Ready for a re-review when time permitted.

**Comment by ParamConstructor** [comment]
@SamuelHassine - This is currently in some re-work - Please do not merge. I'll re-comment when ready.

**Comment by jpkha** [comment]
Hello @ParamConstructor,

Thank you for your work.
Unfortunately, the team opted for Playwright.
Here's the PR: https://github.com/OpenCTI-Platform/opencti/pull/5555.

We've tried to match your scenario for login/logout.
For the login, we've implemented a login/password scenario and added a logout function.

Additionally, we've included two scenarios: creating and updating a report.
And also a step test:e2e in drone.

If you have any questions or doubts, please feel free to ask.

**Pull request closed without merging**
