### PR TITLE
[graphql] Replace redlock@5.0.0-beta.2 w/ @sesamecare-oss/redlock@1.2.1

### PR DESCRIPTION
**Pull request by ckane**
### Proposed changes
Replace `redlock` TS module with `@sesamecare-oss/redlock` which is a rewrite of the algorithm. The older `redlock` project hasn't released a new release since a 5.0.0 beta in March of 2023.

### Related issues

This was discussed in #6285 - it is not yet determined if this will address the reported problems. I am currently doing some testing, but wanted to open the PR as a preliminary reference for tracking the code changes that need to occur

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by ckane** [comment]
This does not solve the problems discussed in #6285 but it has been working without regressions for two days on my instances

**Comment by ckane** [comment]
> This does not solve the problems discussed in #6285 but it has been working without regressions for two days on my instances

The problems discussed in #6285 were fixed in #6640, but still recommend this change due to upstream maintenance state of current `redlock` package

**Comment by ckane** [comment]
Rebased against current `master` branch, and also updated the version of redlock to latest `1.3.1`

**Comment by ckane** [comment]
Also not sure what I need to do to clear the "lockfile would be updated" error in the api-tests in the drone CI run. My expectation is I did the `npm`/`yarn` upgrade incorrectly and there's something else which needs to be updated too. If you point me at what I need to do I'll fix it and update my tree as well.

**Comment by richard-julien** [comment]
Really sorry about this one @ckane , will do some test and merge that in couple of weeks.
For yarn locks you can remove the lock file and regenerate it with yarn install, should resolve the conflicts.

**Comment by ckane** [comment]
Ok thanks @richard-julien - I just pushed a missing dependency that hopefully fixes it. Also re-committed my commits as signed, which I forgot to do earlier.

**Comment by richard-julien** [comment]
Hi @ckane , can you remove "redlock": "5.0.0-beta.2" in package.json and redo a yarn install.
I think its the reason the PR fail.
Thanks

**Comment by ckane** [comment]
> Hi @ckane , can you remove "redlock": "5.0.0-beta.2" in package.json and redo a yarn install. I think its the reason the PR fail. Thanks

Thanks @richard-julien, I messed up the rebase. Should be good now.

**Comment by richard-julien** [comment]
Hi @ckane , Im really sorry, im back after some inactivity period, and just change the target from master to 6.5.0.
Looks like there is a conflict :( Can you rebase again and then I will merge the PR ... finally :)

**Comment by ckane** [comment]
> Hi @ckane , Im really sorry, im back after some inactivity period, and just change the target from master to 6.5.0. Looks like there is a conflict :( Can you rebase again and then I will merge the PR ... finally :)

No worries - should be rebased against `release/6.5.0` now

**Comment by ckane** [comment]
Hm looks like it pulled in a whole bunch of other commits or something. I will try branching a new branch from `release/6.5.0` and manually cherry-pick the relevant commits to that

**Comment by richard-julien** [comment]
Merged for 6.5.0. Thanks @ckane

**Pull request merged**
