### PR TITLE
[backend] replace plyara with yara-python for yara indicator check (#8291)

### LINKED ISSUE #8291: OpenCTI failed to validate YARA rules containing "\r" escape sequence in text strings.
## Description

OpenCTI failed to validate and import YARA rules containing "\r" escape sequence in text strings.

## Environment

2. OpenCTI version: 6.2.18

## Reproducible Steps

Import a YARA rule containing the "\r" escape sequence in text strings.

### PR DESCRIPTION
**Pull request by JeremyCloarec**
### Proposed changes

* replaced no longer maintained plyara library with yara-python library

### Related issues

* #8291 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by aHenryJard** [comment]
I see plyara lib at several places in connector, do we need to move them all to yara-python for consistency ?
https://github.com/search?q=org%3AOpenCTI-Platform%20plyara&type=code

**Comment by JeremyCloarec** [comment]
You're right, I'll update them as well

**Comment by JeremyCloarec** [comment]
After discussing it with @romain-filigran , we will merge this PR and create a separate issue https://github.com/OpenCTI-Platform/connectors/issues/2830 for switching the libraries used in the connectors

**Review by marieflorescontact — APPROVED** [review]
functionnaly tested ok with correctly and not correctly formated YARA rules 👌

**Pull request merged**
