### PR TITLE
[backend] Fix handling of platform_entity_files_ref config (#7406)

### PR DESCRIPTION
**Pull request by JeremyCloarec**
### Proposed changes

* Added fileId to external reference schema attributes
* Fixed creation of external ref in createEntityRaw when platform_entity_files_ref is configured
* Fixed updater for external ref deletion

### Related issues

* #7406 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case (coverage and e2e)
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Comment by Archidoit** [comment]
Creation works but we can't delete or remove the external ref from the entity.

- Enforce external ref creation at file upload for Malwares
- Create a malware with a file
- An external reference associated with the file is well created and well associated to the malware
- But you can't remove / delete the external ref from the malware

image

If you click on 'delete', the file is deleted but the external ref is still there : 
image

If you try to delete again, error message : 
image

**Comment by Kedae** [comment]
Have you checked stixCoreObject@stixCoreObjectsImportPush ?

**Comment by JeremyCloarec** [comment]
Yes, tested both entity creation and import push behavior. stixCoreObjectsImportPush was working properly once fileId was added back as an external ref attribute

**Comment by Archidoit** [comment]
We have only the choices 'update' or 'delete'. 
image

We should also have 'remove', like it is proposed when we add the external ref after creation via the 'add' button : 
image

What's more, when we click on 'delete', the external ref is from the object. But if you reload the external ref still apears (but without the file). And the external ref is still present (it has not been deleted from the platform) : 
image

**Comment by Archidoit** [comment]
Create an object with a file, an external reference with the file is created.

Go to an entity overview.
Click on 'add external reference' : 
image

You can't select the external references created via the file upload (see test.txt in the list of the screenshot below) : 
image

**Comment by Archidoit** [comment]
Create an entity with a file. The external ref is well created.
Click on Update the external ref : 
image

Change the source name. An error occurs for the URL field : 
image

But the external ref is well updated if we leave the edition form : 
image

**Comment by JeremyCloarec** [comment]
URL validation problem has been moved to a separate issue: https://github.com/OpenCTI-Platform/opencti/issues/7431

**Review by Archidoit — APPROVED** [review]

**Comment by JeremyCloarec** [comment]
The questions about the expected behavior of these external references have been moved to this issue https://github.com/OpenCTI-Platform/opencti/issues/7432

**Pull request merged**
