### PR TITLE
[frontend] fix position of ai button

### PR DESCRIPTION
**Pull request by frapuks**
### Proposed changes

- Update position of ai button in RichTextField variant html

### Related issues

- Overlay between fullscreen button and ai button

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Review by marieflorescontact — APPROVED** [review]

**Comment by SamuelHassine** [comment]
Can you post a screenshot of the new position please?

**Comment by marieflorescontact** [comment]
> Can you post a screenshot of the new position please?

image

**Comment by SamuelHassine** [comment]
Can you check the behavior in Report => Content => New HTML file?

**Comment by frapuks** [comment]
> Can you check the behavior in Report => Content => New HTML file?

Broken
image

expected behaviour is this ?
image

**Update** : add style to differentiate 2 cases

**Comment by frapuks** [comment]
> > Can you check the behavior in Report => Content => New HTML file?
> 
> Broken image
> 
> expected behaviour is this ? image

Update : add style to differentiate 2 cases

**Pull request merged**
